import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import * as React from 'react'
import { useForm } from 'react-hook-form'

const Home: NextPage = () => {
  
  const {register, handleSubmit, formState: {errors}} = useForm();

  const onSubmit = (data) => {
    console.log(data)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <nav className={styles.navbar}>
    
         <h1 className={styles.navbarTitle}>AutoCommerce</h1>
     
         <ul className={styles.navItems}>
       
           <li>Home</li>
           <li>About</li>
           <li>Shop</li>
           <li>Contact</li>
       
        </ul>
    
        <ul className={styles.navIcons}>
      
          <i class="fas fa-search"></i>
          <i class="fas fa-shopping-cart"></i>
      
        </ul>

       </nav>

       <div className={styles.loginFormContainer}>

        <div className={styles.loginForm}>
      
          <p className={styles.loginFormTitle}>ADMIN</p>

          <form onSubmit={handleSubmit(onSubmit)}>

            <label htmlFor="email">Email</label>
            <input type="email" name="email" placeholder="Email..." {...register('email', {required: true})} />
            {errors.email && <p>Email is invalid</p>}
 
            <label htmlFor="password">Password</label>
            <input type="password" name="password" placeholder="Password..." {...register('password', {required: true, minLength: 8})} />
            {errors.password && <p>Password is invalid</p>}
            <button type="submit">LOGIN</button>

          </form>

        </div>

       </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
